-- 기존 테이블이 있다면 삭제 (초기화용)
DROP TABLE IF EXISTS test;

-- 일기(daily_diaries) 테이블 생성
CREATE TABLE test (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- id 컬럼 (Long 타입 대응)
    content TEXT NOT NULL,                                   -- content 컬럼 (String 타입 대응)
    reg_dt DATE DEFAULT CURRENT_DATE
);
-- 테스트 데이터 입력
INSERT INTO test (content, reg_dt) VALUES ('첫 번째 일기 내용입니다.', '2025-12-24');
INSERT INTO test (content, reg_dt) VALUES ('오늘은 스프링 부트와 JDBC를 공부했습니다.', '2025-12-25');
INSERT INTO test (content, reg_dt) VALUES ('내일은 일기 등록 기능을 만들어볼 예정입니다.', '2025-12-26');